#!/bin/bash

# Script for updating database. This should be run a a regular cron job to keep DB up to date. 
# Michael S. Hansen (michael.hansen@nih.gov)
#
# Run with:
#
#   ./update_database <DATABASE PATH> <PATH TO LOOK FOR NEW STUDIES> <REMOVE FROM PATH>


dbpath=$1
source_path=$2
remove_path=$3

newest_file=$(find $dbpath -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
for d in $(find $source_path -mindepth 1 -maxdepth 1 -type d -newer $newest_file); do
    find $d -name "*.dat" -exec addfile -b $remove_path -d $dbpath {} \;
done
